volumes:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/node_modules
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    environment:
      WATCHPACK_POLLING: true
    stdin_open: true
    tty: true
  
  postgres:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  adminer:
    image: adminer:4.17.1-standalone
    container_name: adminer-container
    hostname: adminer
    ports:
      - "8080:8080"
    # deppends_on:
    #   postgres:
    #     condition: service_healthy
    #     restart: true

  redis:
    image: redis:7.4.2-bookworm
    container_name: redis-container
    hostname: redis
    ports:
      - "6379:6379"
  