[QC_Thresholds]
GQ = 20
DP = 5
AB_het = 0.2
AB_hom = 0.02

[In_silico_predictions]
# Thresholds for hard filter
SIFT = 0.05
PolyPhen-2 = 0.446 
exclude_MutationTaster = ["polymorphism_automatic", "polymorphism"]
CADD = 10

[AF_Thresholds]
GGM = 0.05