
# ToMMo 54KJPN
[[annotation]]
file="resources/tommo_54kjpn.vcf.gz"
# the special name 'ID' pulls out the rs id from the VCF
fields = ["AC_AFR", "AC_AMR", "AC_EAS", "ID"]
ops=["first", "first", "first", "first"]

# JARVIS
[[annotation]]
# count is for alignments that are mapped (-F4) with mapq > 0
file="example/ex.bam"
names=["mapq", "coverage", "xdp2"] # map, coverage, and seq are special values for bam annotations
fields=["mapq", "coverage", "DP2"]
ops=["mean", "sum", "DP2"] # op can be anything for DP2 field.

# TraP
[[annotation]]
file=""
names=[""]
fields=["TraP"]
ops=["self"]