services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: .
        target: /work