version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s [%(levelname)-7s] (%(name)-13s) - %(message)s'
    datefmt: '%Y/%m/%d %I:%M:%S'
  detailed:
    format: '%(asctime)s [%(levelname)-7s] (%(name)s:%(lineno)d) - %(message)s'
    datefmt: '%Y/%m/%d %I:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: annolinks.log
    encoding: utf-8
    maxBytes: 10000
    backupCount: 1

loggers:
  annolinks.cli:
    level: INFO
    handlers: [console, file]
    propagate: no
  hyperlink:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  args:
    level: INFO
    handlers: [console, file]
    propagate: no
  errcheck:
    level: INFO
    handlers: [console, file]
    propagate: no
  preprocess:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: ERROR
  handlers: [file]