gnomad40_genome_af: 0.01
gnomad40_genome_af_afr: 0.01
gnomad40_genome_af_ami: 0.01
gnomad40_genome_af_amr: 0.01
gnomad40_genome_af_asj: 0.01
gnomad40_genome_af_eas: 0.01
gnomad40_genome_af_fin: 0.01
gnomad40_genome_af_mid: 0.01
gnomad40_genome_af_nfe: 0.01
gnomad40_genome_af_remaining: 0.01
gnomad40_genome_af_sas: 0.01
all_sites_2015_08: 0.01
hrc_af: 0.01
hrc_non1000g_af: 0.01
kaviar_af: 0.01
gme_af: 0.01
gme_nwa: 0.01
gme_nea: 0.01
gme_ap: 0.01
gme_israel: 0.01
gme_sd: 0.01
gme_tp: 0.01
gme_ca: 0.01