services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb_hgmd-${HGMD_VERSION}
    # env_file:
    #   - ./config/build_env
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=default_db
      - MARIADB_USER=hgmd
      - MARIADB_PASSWORD=test
      - TZ='Asia/Tokyo'
      - HGMD_VERSION=${HGMD_VERSION}
      - BIND_ADDRESS=0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./mariadb_data
        target: /var/lib/mysql
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ${DUMP_DIR}
        target: /dump_files
    healthcheck: # Using healthcheck.sh script from MariaDB official image
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 20s