services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5505:80"
    volumes:
      - type: bind
        source: ../
        target: /workspace
    stdin_open: true
    tty: true